### ISSUE TITLE
Mismatch on Recovery Point Objective

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/activity-tracker#19]
For Activity Tracker, on the High Availability and Disaster recovery page, under the heading "DR Recovery Time" there is a table which says:

Recovery objective for DR | Estimated time
-- | --
Maximum Tolerable Downtime (MTD) / Recovery Time Objective (RTO) | Less than 24 hours
Recovery Point Objective (RPO) | Less than 4 hours

However, in the text immediately above there is a statement which reads:

"Data and the auditing metadata such as dashboards, alerts, views, screens, templates are backed up every 24 hours. In the event of an un-recoverable disaster, up to 24 hours of data and metadata changes to the auditing instance in the failure region can be lost."

So surely the Recovery Point Objective can be 'Less than 24 hours' at best and not 4 hours as stated, as the previous statement says up to 24 hours of data can be lost?

**Comment by vanadiscrawford** [comment]
@jamesbeltonIBM Thank you for bringing this to our attention. We have opened an issue in our internal repo to clarify the information.
